# Site settings
title: Prahara
email: hardwinder@gmail.com
url: https://hardwinder.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
skills: "Eat - Play - Sleep"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: hardwinder
  location: Location
  social: Other Links
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/hardwinder
  - title: facebook
    url: https://facebook.com/harwin.prahara
  - title: github
    url: https://github.com/hardwinder

# Postal address (add as many lines as necessary)
address:
  - line: Menteng Square SOHO Tower A 22 no. 15
  - line: Jakarta, Indonesia

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
